"""CurseForge API v1 client.

Base: https://api.curseforge.com
Dokümantasyon: https://docs.curseforge.com/rest-api/
- `x-api-key` header ZORUNLU (kullanıcı ayarlarından okunur, koda gömülmez).
- Minecraft gameId = 432, mod classId = 6.
- CurseForge, Modrinth'in aksine client/server "env" bilgisini standart
  olarak vermez; bu yüzden server pack filtrelemesinde CF modları için
  data/client_only_mods.json'daki bilinen liste devreye girer.
"""

from __future__ import annotations

import httpx

from mcpack.downloader import make_client
from mcpack.models import ContentKind, Loader, ModSourceType
from mcpack.sources.base import (
    ModDetail,
    ModSource,
    ModVersion,
    SearchResult,
    SourceAPIError,
    VersionDependency,
    VersionFile,
)

BASE_URL = "https://api.curseforge.com"
MINECRAFT_GAME_ID = 432
MOD_CLASS_ID = 6

_CLASS_ID = {
    ContentKind.SHADERPACK: 6552,
    ContentKind.RESOURCEPACK: 12,
    ContentKind.DATAPACK: 6945,
    ContentKind.WORLD: 17,
}
"""CurseForge Minecraft (gameId 432) alt kategori classId'leri
(https://api.curseforge.com/v1/categories?gameId=432 ile doğrulandı)."""

_LOADER_TO_CF = {
    Loader.FORGE: 1,
    Loader.FABRIC: 4,
    Loader.QUILT: 5,
    Loader.NEOFORGE: 6,
}

_RELATION_TYPE_MAP = {
    1: "embedded",
    2: "optional",
    3: "required",
    4: "tool",
    5: "incompatible",
    6: "embedded",
}


class CurseForgeConfigError(Exception):
    """API key ayarlanmamışsa fırlatılır."""


class CurseForgeClient(ModSource):
    name = ModSourceType.CURSEFORGE

    def __init__(self, api_key: str, client: httpx.AsyncClient | None = None) -> None:
        if not api_key:
            raise CurseForgeConfigError(
                "CurseForge API key ayarlanmamış. Ayarlar'dan girmelisiniz."
            )
        self._api_key = api_key
        self._client = client or make_client(extra_headers={"x-api-key": api_key})
        self._owns_client = client is None

    async def aclose(self) -> None:
        if self._owns_client:
            await self._client.aclose()

    async def check_connection(self) -> str:
        """Ayarlar penceresindeki "Bağlantıyı Test Et" butonu için — key
        geçersizse/yetkisizse _get zaten 403'ü net bir SourceAPIError'a
        çeviriyor (bkz. yukarısı), burada sadece başarılıysa oyunun adını
        döndürüyoruz ki kullanıcı sadece "bağlandı" değil neye bağlandığını
        da görsün."""
        response = await self._get(f"/v1/games/{MINECRAFT_GAME_ID}")
        data = response.json().get("data", {})
        return data.get("name", "Minecraft")

    async def _get(self, path: str, params: dict | None = None) -> httpx.Response:
        try:
            response = await self._client.get(f"{BASE_URL}{path}", params=params)
            response.raise_for_status()
        except httpx.HTTPStatusError as exc:
            status = exc.response.status_code
            if status in (401, 403):
                raise SourceAPIError(await self._describe_auth_error(exc.response, path)) from exc
            if status == 404:
                raise SourceAPIError(f"CurseForge'ta bulunamadı: {path}") from exc
            raise SourceAPIError(f"CurseForge API hatası ({status}): {path}") from exc
        except httpx.RequestError as exc:
            raise SourceAPIError(f"CurseForge API'sine ulaşılamadı (ağ hatası): {exc}") from exc
        return response

    async def _key_is_valid(self) -> bool:
        """Key'i, sadece geçerli key ile çalışan arama uç noktasıyla yoklar.

        CurseForge bazı key'lere kısıtlı yetki veriyor: arama 200 dönerken
        mod detayı/dosyalar/games 403 dönebiliyor. Bu yoklama "key geçersiz"
        ile "key geçerli ama bu işleme yetkisi yok" ayrımını yapmamızı sağlar.
        """
        try:
            response = await self._client.get(
                f"{BASE_URL}/v1/mods/search", params={"gameId": MINECRAFT_GAME_ID, "pageSize": 1}
            )
        except httpx.RequestError:
            return False
        return response.status_code == 200

    async def _describe_auth_error(self, response: httpx.Response, path: str) -> str:
        """401/403 için neyin ters gittiğini ayırt eden mesaj üretir.

        Dikkat: `x-cache: Error from cloudfront` başlığı CloudFront'un
        arkasındaki sunucu HERHANGİ bir hata döndürdüğünde de gelir; tek
        başına "CDN engeli" kanıtı değildir. Gerçek CloudFront/WAF engeli
        "The request could not be satisfied" yazan bir HTML sayfası döndürür.
        CurseForge'un kendisi geçersiz key'i ise boş gövdeli 403 ile reddeder.
        """
        status = response.status_code
        body = response.text or ""
        cf_id = response.headers.get("x-amz-cf-id", "")
        suffix = f" (HTTP {status}" + (f", CloudFront ID: {cf_id}" if cf_id else "") + ")"

        if "could not be satisfied" in body.lower() or "generated by cloudfront" in body.lower():
            return (
                "CurseForge isteği CDN (CloudFront) tarafından engellendi — sorun API key'de "
                "değil, ağınızda/IP adresinizde. VPN/farklı ağ deneyin veya CloudFront ID ile "
                "CurseForge desteğine yazın." + suffix
            )

        if not path.startswith("/v1/mods/search") and await self._key_is_valid():
            return (
                f"CurseForge API key geçerli (arama çalışıyor) ama bu işleme yetkisi yok: {path}. "
                "Key'in erişimi kısıtlanmış görünüyor — console.curseforge.com'da key'in "
                "durumunu/onayını kontrol edin veya CurseForge desteğine CloudFront ID ile "
                "yazın." + suffix
            )

        key = self._api_key.strip()
        if key != self._api_key:
            hint = "Key'in başında/sonunda boşluk var; silip tekrar yapıştırın."
        elif not key.startswith("$2a$") or len(key) != 60:
            hint = (
                "Key biçimi beklenene benzemiyor (normalde '$2a$10$' ile başlayan 60 karakter; "
                f"girilen {len(key)} karakter). Eksik/fazla kopyalanmış olabilir."
            )
        else:
            hint = (
                "Key biçimi doğru görünüyor ama CurseForge kabul etmiyor — büyük ihtimalle "
                "iptal edilmiş veya yenilenmiş. console.curseforge.com → API Keys'ten yeni key "
                "alıp Ayarlar'a girin."
            )
        return "CurseForge API key reddedildi. " + hint + suffix

    async def search(
        self,
        query: str,
        *,
        game_version: str | None = None,
        loader: Loader | None = None,
        content_kind: ContentKind | None = None,
        limit: int = 20,
        offset: int = 0,
    ) -> list[SearchResult]:
        class_id = _CLASS_ID.get(content_kind, MOD_CLASS_ID) if content_kind else MOD_CLASS_ID
        params: dict[str, str | int] = {
            "gameId": MINECRAFT_GAME_ID,
            "classId": class_id,
            "searchFilter": query,
            "pageSize": limit,
            "index": offset,
        }
        if game_version:
            params["gameVersion"] = game_version
        # modLoaderType sadece mod aramasında anlamlı.
        if class_id == MOD_CLASS_ID and loader and loader in _LOADER_TO_CF:
            params["modLoaderType"] = _LOADER_TO_CF[loader]

        response = await self._get("/v1/mods/search", params=params)
        data = response.json().get("data", [])

        return [
            SearchResult(
                source=self.name,
                project_id=str(mod["id"]),
                slug=mod.get("slug", ""),
                title=mod["name"],
                description=mod.get("summary", ""),
                icon_url=(mod.get("logo") or {}).get("thumbnailUrl"),
                downloads=int(mod.get("downloadCount", 0)),
                categories=[c.get("name", "") for c in mod.get("categories", [])],
            )
            for mod in data
        ]

    async def get_project(self, project_id: str) -> ModDetail:
        response = await self._get(f"/v1/mods/{project_id}")
        mod = response.json()["data"]
        return ModDetail(
            source=self.name,
            project_id=str(mod["id"]),
            slug=mod.get("slug", ""),
            title=mod["name"],
            description=mod.get("summary", ""),
            categories=[c.get("name", "") for c in mod.get("categories", [])],
        )

    async def get_versions(
        self,
        project_id: str,
        *,
        game_version: str | None = None,
        loader: Loader | None = None,
    ) -> list[ModVersion]:
        params: dict[str, str | int] = {}
        if game_version:
            params["gameVersion"] = game_version
        if loader and loader in _LOADER_TO_CF:
            params["modLoaderType"] = _LOADER_TO_CF[loader]

        response = await self._get(f"/v1/mods/{project_id}/files", params=params)
        data = response.json().get("data", [])

        versions = []
        for f in data:
            sha1 = next(
                (h["value"] for h in f.get("hashes", []) if h.get("algo") == 1), None
            )
            download_url = f.get("downloadUrl")
            if not download_url:
                # Bazı modlarda yayıncı "3rd party download" iznini kapatmıştır;
                # bu durumda downloadUrl None gelir ve indirme mümkün olmaz.
                continue

            deps = [
                VersionDependency(
                    project_id=str(d["modId"]),
                    dependency_type=_RELATION_TYPE_MAP.get(d.get("relationType", 3), "required"),
                )
                for d in f.get("dependencies", [])
            ]

            versions.append(
                ModVersion(
                    source=self.name,
                    version_id=str(f["id"]),
                    project_id=str(f["modId"]),
                    name=f.get("displayName", f.get("fileName", "")),
                    game_versions=[gv for gv in f.get("gameVersions", [])],
                    loaders=[loader.value] if loader else [],
                    dependencies=deps,
                    files=[
                        VersionFile(
                            file_name=f["fileName"],
                            url=download_url,
                            sha1=sha1,
                            size=f.get("fileLength"),
                            primary=True,
                        )
                    ],
                )
            )
        return versions

    async def get_download_url(self, project_id: str, file_id: str) -> str:
        """downloadUrl None gelen dosyalar için ayrı endpoint (bazı durumlarda hâlâ boş dönebilir)."""
        response = await self._get(f"/v1/mods/{project_id}/files/{file_id}/download-url")
        return response.json()["data"]
